### ISSUE TITLE
what does this error mean?

### ISSUE THREAD

**Issue by wjlei1990** [chukren/pyadjoint#6] opened 2016-03-08 04:08 UTC
Hi Youyi,

I noticed there are errors:

```
Error during the processing of station 'II.TAU' on rank 0:
Traceback (At max 3 levels - most recent call last):
  File "/autofs/nccs-svm1_home1/lei/software/pypaw/src/pypaw/procbase.py", line 206, in smart_run
    self._core(path, param)
  File "/autofs/nccs-svm1_home1/lei/software/pypaw/src/pypaw/adjoint.py", line 226, in _core
    output_filename)
  File "/autofs/nccs-svm1_home1/lei/software/wenjie/pyasdf/pyasdf/asdf_data_set.py", line 1423, in process_two_files
    getattr(other_ds.waveforms, station))
  File "/autofs/nccs-svm1_home1/lei/software/pypaw/src/pypaw/adjoint.py", line 93, in adjoint_wrapper
    adjoint_src_flag=adjoint_src_flag)
  File "/autofs/nccs-svm1_home1/lei/software/pytomo3d/pytomo3d/adjoint/adjsrc.py", line 183, in calculate_adjsrc_on_stream
    figure_mode=figure_mode, figure_dir=figure_dir)
  File "/autofs/nccs-svm1_home1/lei/software/pytomo3d/pytomo3d/adjoint/adjsrc.py", line 113, in calculate_adjsrc_on_trace
    plot=figure_mode)
  File "/autofs/nccs-svm1_home1/lei/software/pyadjoint/src/pyadjoint/adjoint_source.py", line 352, in calculate_adjoint_source
    "The underlying function returned an adjoint source with "

PyadjointError: The underlying function returned an adjoint source with either NaNs or Inf values. This must not be.
```

Is it normal? Or it is just the way it should be?

**Comment by chukren** [comment] 2016-03-08 04:39
That doesn't look right, it might be a hidden bug but I am not sure.  Can you please tell me the event id so I can take a look?

**Comment by wjlei1990** [comment] 2016-03-08 13:35
It is in this dir:
`/lustre/atlas/proj-shared/geo111/Wenjie/bm_workflow/examples/adjoint_sources`
on rhea.

Let me know if you can get access.

**Comment by chukren** [comment] 2016-03-08 16:56
Thanks for the catch. It caused by a very narrow frequency band in multi-taper measurements. Bug fixed version committed.

**Closed as completed by chukren** 2016-03-08 16:56 UTC
